### PR TITLE
Retain parameters in user-facing panels between instantiations

### PR DESCRIPTION
**Pull request by seanwarren**
Our group has recently come across QuPath and it seems to be very useful - thanks for sharing this tool!

One comment has been that user parameters are lost when a tool panel is closed. This can be a bit frustrating if you've spent a while optimising the parameters.  

This PR makes user-facing parameters persistent between instantiations of the panel (and indeed program) using the Java Preferences API. The default parameters are used in the first instance but are overridden once the user has established new parameters. I'm afraid it touches quite a few files but mostly trivially as the modified ParameterList needs to know where it is being called from.

### CODE REVIEW

**Comment by petebankhead** [comment]
Thanks, this looks like a really neat approach to making the parameters persistent.

I've also suffered from the 'lost parameters' in the past.  However there actually is already a solution/workaround: if you select the *Workflow* tab and then double-click on any previous logged setting for a command (e.g. cell detection) then it will show the parameter dialog with the same values.

This has the advantage of making it possible to return to *any* parameters previously applied for that image (even during different sessions), not just the most recent ones.

It's also possible to apply a command with the same parameters to another image, either by
* keeping the dialog open when changing image, or
* running a one-line script version of the command

Because the script version is also logged in the workflow, double-clicking can again be used - giving a mechanism to transfer the settings *and* still launch a dialog for any further tweaking.

And there's the option to store such scripts inside the 'scripts' directory of the project, so that they can be retrieved from within the *Automate &rarr; Project scripts...* menu.

I'm a bit apprehensive about storing the last parameters in the preferences because
* it makes it harder to return to the defaults
* sometimes some of the the default parameters have a dependency on the image type (e.g. fluorescence or brightfield), and this may risk confusion (e.g. if defaults for fluorescence get mixed up with those with brightfield)
* when teaching the software, it's useful to be able to say things like 'try the defaults first, and then adjust parameter A if it detects too much/too little/too fragmented etc.'  But that gets more complicated if it's not possible to know what the defaults will be for the user at any time
* it can be easy to get into the habit of just assuming the parameters are the same as before and running the command without checking.  But then if someone else used the software in the meantime, or the preferences were reset, this could lead to using unintended parameters being applied.

For me, the workflow trick is enough to avoid the annoyance and I would tend towards just relying on that for the reasons above, although am open to being convinced otherwise.

I do certainly think the method of handling parameters has some room for improvement.  I have wondered if they should be generated by annotations (more like ImageJ2?), and also think the ability to stash particular collections of parameters with certain names (e.g. 'Cell detection for X stains, Y scanner') could be useful as well.  But these would potentially be bigger changes; I'm also not sure where they should be stored, or how such an option should be presented in the UI.

What do you think?

**Comment by seanwarren** [comment]
Hi Pete, thanks for your prompt reply. I hadn't realised it was possible to reopen the dialog box in that way, I'll give that a go and see how people get on with it - at the moment there is quite a bit of screenshotting which isn't ideal. 

I take your point about a multiuser system - that isn't really a problem for us as we have individual logins for the analysis workstations so everyone has their own preferences. I can see this leading to confusion if you have more than one user though! 

What do you think about adding a 'Reset to defaults' button to the bottom of the panels? This could be done automatically in a reasonably straightforward way I think. That might avoid some of the potential pitfalls as they'd always be an easy way to get back to somewhere sensible (this would include any dynamic brightfield/fluorescence settings).

In a similar vein, it might be possible to add a small save/load option to each panel to allow the user to stash different settings. I'd have to have a think about how easily that could be implemented in a general way.

**Comment by petebankhead** [comment]
Oh dear, yes screenshotting doesn't sound ideal... at the very least, saving the script line from the *Workflow* pane should give a fairly readable (albeit lengthy) record of the parameters.

In v0.1.2 the parameters always had to be passed as a single line in the script (no pretty-printing), but that limitation should not be present on this fork.

Personally, I'd prefer to keep the default option being to not persist the parameters, and to rely primarily on the *Workflow* tab method.  I think storing & restoring parameters should be an active choice.

If there were to be a way to make parameters persistent, it would ideally be in as unobtrusive a way as possible, as the dialogs are already intimidatingly big in some cases.

I'm also unclear on where it would make sense to store the parameters.  I could imagine there being a desire to transfer them between computers, so somewhere in the 'extensions' directory might be preferable to the preferences.  But since it's not an extension that would be a bit of a hack...

With a bit of thinking and discussion that could maybe be generalized more and made useful in other ways (e.g. including log files?).

One of the main places where the absence of persistence bothers me most is when it comes to setting stain vectors for color deconvolution.  I'd ideally like a way to store, export and import a user-defined list of vectors.

> Sidenote: I find the Java preferences to be a bit brittle; I lose mine from time-to-time without warning.  I have a suspicion it is related to running the Fiji updater while QuPath is open - but I'm not certain about that.  My setup is rather non-standard, mostly running QuPath in debug mode through an IDE so maybe it doesn't happen under more normal circumstances.  
> 
> Have you seen this at all?

**Comment by petebankhead** [comment]
PS. I started a blog earlier this week to write about & discuss various QuPath-related things, as well as plans and technical details: http://petebankhead.github.io

**Comment by seanwarren** [comment]
No problem, I understand your logic. I'm afraid that I probably don't have time to look at implementing a more systematic approach to this at the moment - I was just getting a bit frustrated when optimising some fluorescence segmentation.

I haven't experienced any problems with the Java preferences so far, but to be honest my Java experience is very limited, I'm mostly a C++ guy :).

**Comment by petebankhead** [comment]
I'll close this as the list of conflicts is growing and I think that double-clicking the entry in the workflow is a more maintainable solution (for now at least).

**Pull request closed without merging**
